unigrasptransformer:
  table:
    enable: true
    size:
    - 0.6
    - 0.6
    - 0.03
    pos:
    - 0.0
    - 0.0
    - 0.25
    rot_xyzw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0

  object:
    enable: true
    spawn_mesh: true
    show_point_cloud: true
    show_pca_axes: true
    static_usd: null
    size:
    - 0.1
    - 0.1
    - 0.1
    pos:
    - 0.0
    - 0.0
    - 0.5
    rot_xyzw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    pc_fps: null
    pca_axes: null
    object_init: null
    
  hand:
    asset_type: shadowhand
    asset_path: /home/chizhang/Tiangong_isaac_rl/legged_lab/assets/shadow_hand_with_fingertip/shadow_hand_right/shadow_hand_right.usd
    pos:
    - 0.5
    - 0.2
    - 0.75
    rot_xyzw:
    - 0.0
    - -0.70710678
    - 0.0
    - 0.70710678
    show_palm_dir: false
    palm_dir_local:
    - 1.0
    - 0.0
    - 0.0
    palm_dir_offset_local:
    - 0.0
    - 0.0
    - 0.0
    palm_dir_scale: 0.2
    warp_on_reset: true
