unigrasptransformer:
  table:
    enable: true
    size:
    - 0.6
    - 0.6
    - 0.03
    pos:
    - 0.0
    - 0.0
    - 0.25
    rot_xyzw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0

  object:
    enable: true
    spawn_mesh: true
    show_point_cloud: true
    show_pca_axes: true
    # Set to a USD file or a dataset object directory containing metadata.json. If null, a dataset object is auto-picked.
    object_path: /home/chizhang/Tiangong_isaac_rl/dataset/unigrasptransformer_asset/meshdatav3_scaled/subset_core10/core/jar-947cf0b19783a119154dddaf2978e13f
    size:
    - 0.1
    - 0.1
    - 0.1
    pos:
    - 0.0
    - 0.0
    - 0.5
    rot_xyzw:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    object_init: null
    
  hand:
    asset_type: shadowhand
    asset_path: /home/chizhang/Tiangong_isaac_rl/legged_lab/assets/shadow_hand_with_fingertip/shadow_hand_right_for_conversion/shadow_hand_right_for_conversion.usd
    pos:
    - 0.5
    - 0.2
    - 0.75
    rot_xyzw:
    - 0.0
    - -0.70710678
    - 0.0
    - 0.70710678
    show_palm_dir: false
    palm_dir_local:
    - 1.0
    - 0.0
    - 0.0
    palm_dir_offset_local:
    - 0.0
    - 0.0
    - 0.0
    palm_dir_scale: 0.2
    warp_on_reset: true

  reward_targets:
    joint_order: ["FFJ4","FFJ3","FFJ2","FFJ1","MFJ4","MFJ3","MFJ2","MFJ1","RFJ4","RFJ3","RFJ2","RFJ1","LFJ5","LFJ4","LFJ3","LFJ2","LFJ1","THJ5","THJ4","THJ3","THJ2","THJ1"]
    init_qpos: [0.1,0.0,0.6,0.0,0.0,0.0,0.6,0.0,-0.1,0.0,0.6,0.0,0.0,-0.2,0.0,0.6,0.0,0.0,1.2,0.0,-0.2,0.0]
    hand_mask: [0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0]
    hand_pose: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
